# App Name
spring.application.name=ordertracker

# PostgreSQL Database Configuration (using orderuser)
spring.datasource.url=jdbc:postgresql://localhost:5432/ordertrackerdb
spring.datasource.username=orderuser
spring.datasource.password=orderpass123

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional: custom port for local testing
server.port=8080
